Reads has been loaded.
Loading ma_hit_ts from disk... 
ma_hit_ts has been read.
Loading ma_hit_ts from disk... 
ma_hit_ts has been read.
[M::ha_assemble::1.426*0.98] ==> loaded corrected reads and overlaps from disk
[M::purge_dups] homozygous read coverage threshold: 8
[M::purge_dups] purge duplication coverage threshold: 10
Writing raw unitig GFA to disk... 
Writing processed unitig GFA to disk... 
[M::purge_dups] homozygous read coverage threshold: 8
[M::purge_dups] purge duplication coverage threshold: 10
[M::mc_solve_core::0.000] ==> Partition
[M::adjust_utg_by_primary] primary contig coverage range: [6, infinity]
Writing ditt_lim_hifiasm_chloroplast.asm.bp.p_ctg.gfa to disk... 
[M::adjust_utg_by_trio] primary contig coverage range: [6, infinity]
Writing ditt_lim_hifiasm_chloroplast.asm.bp.hap1.p_ctg.gfa to disk... 
[M::adjust_utg_by_trio] primary contig coverage range: [6, infinity]
Writing ditt_lim_hifiasm_chloroplast.asm.bp.hap2.p_ctg.gfa to disk... 
Inconsistency threshold for low-quality regions in BED files: 70%
[M::main] Version: 0.16.1-r375
[M::main] CMD: hifiasm -o ditt_lim_hifiasm_chloroplast.asm -t 24 ../dittreads_lim_asm_mapped.fastq
[M::main] Real time: 14.769 sec; CPU: 15.042 sec; Peak RSS: 0.311 GB
